# Generated by Django 5.2.5 on 2025-10-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingPlanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
